### PR TITLE
Update CKEditor to 4.16.1 for a security issue for ckeditor < 4.15.1 (#1484)

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @julien,

Attached is an update for #1484.  This provides an update to CKEditor  to v4.16.1 for a security issue for ckeditor < 4.15.1.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by julien** [comment]
Hi @jonmak08,

I fetched this branch, ran the `yarn build` and `yarn` script to test these changes in my browser, and everything worked as expected. I also tried building locally (in a separate branch based on `master`), just to compare with your changes, but, I wasn't able to.

When I try to build ckeditor with: 

```sh
./scripts/build/build-ckeditor.sh 4.16.1
```

I'm getting the following output:

```sh
$ ./scripts/build/build-ckeditor.sh 4.16.1
HEAD is now at eb2d11644 Changelog corrected.
Previous HEAD position was eb2d11644 Changelog corrected.
HEAD is now at cae20318d CKEditor 4.16.1 changelog corrected.
dev/builder/build.sh: 1: ﻿#!/bin/bash: not found
CKBuilder - Builds a release version of ckeditor4.

dev/builder/build.sh: 20: function: not found
```

I've tried with `bash` and `zsh`, here's more information just in case it's useful. 
Output of `bash --version`

```sh
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Output of `zsh --version`

```sh
% zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

I can't judge if this is 100% OK or not, and what I find strange is that I've never had the problem with the [`liferay/liferay-ckeditor`](https://github.com/liferay/liferay-ckeditor) repository, which uses the same [`build.sh`](https://github.com/ckeditor/ckeditor4/blob/17a1555f7fbb0e83f737c9efe27650dca8dff36f/dev/builder/build.sh) script from [`ckeditor-dev`](https://github.com/ckeditor/ckeditor4/tree/17a1555f7fbb0e83f737c9efe27650dca8dff36f) for the [`build`](https://github.com/liferay/liferay-ckeditor/blob/master/ck.sh#L108-L114) command.

Since you mentioned it on Slack, I'd also make sure to add all changes in the git submodule (including the `lib/ckeditor-dev/dev/builder/build-config.js` file) since that's not ours, and we want to use the default ckeditor4 config when it's "bundled" with alloyeditor.

I would suggest sending a draft pull request to [`liferay/liferay-ckeditor`](https://github.com/liferay/liferay-ckeditor) and have it test by the dxp squad, since I know some also use linux.

Good luck

**Comment by julien** [comment]
Closing here just to avoid an accidental merge.

**Comment by alk-mandrianarijaona** [comment]
Hello @jonmak08 @julien,

I have also created the same PR a few days ago https://github.com/liferay/alloy-editor/pull/1485/files. So should I close it or what do you think?

Regards

**Comment by jonmak08** [comment]
Hey @alk-mandrianarijaona,

Thank you for sending the changes over for us to review.  We really appreciate your efforts in making our product better and more secure.  We would not be where we are without community members like yourself who contribute in making improvements to our product.

After reviewing the pull request you sent (https://github.com/liferay/alloy-editor/pull/1485), it looks like there are some additional files in your pull request when compared to this one.  I think we will go with this pull request for now.  I will comment and update your pull request with links to this one.

Please let me know if you have any questions. Thank you again for all your help!

**Comment by alk-mandrianarijaona** [comment]
Hello @jonmak08, thanks for your comment. I will close my PR then.

Regards

**Pull request closed without merging**
